name = "EasyHPC"
uuid = "d5bee3f7-410e-4906-9c72-b871de41db93"
authors = ["Mahmoud Malla Ali <mahmoud.malla.ali@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Documenter = "1.14.1"
OhMyThreads = "0.8.3"
SpecialFunctions = "2.5.1"
