name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.11"

      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'

      - name: Install package
        run: julia --project=docs -e 'using Pkg; Pkg.develop(path=".")'

      - name: Build and deploy documentation
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs docs/make.jl
